UnBArqDsw2021-1/2021.1_G02_TaNaMesa_docs

docs/seminario1/benchmarking.md

Resolves #
#6 
Cria documento de benchmarking.
Verificar os seguintes pontos:

Cria documento de benchmarking

---

docs/seminario1/personas.md

Resolve #25
Criação do documento contendo descrição, motivação, escolhas, 4 personas, bibliografia e versionamento.

Criação do documento de personas

---

docs/seminario1/instrospeccao.md
docs/seminario1/introspeccao.md

Resolve #26
Elicitação de requisitos utilizando introspecção.

Criação do documento de introspecção

---

docs/seminario1/entrevistas/entrevista.md
docs/seminario1/entrevistas/entrevista_1.md
docs/seminario1/entrevistas/entrevista_2.md
docs/seminario1/entrevistas/entrevista_3.md
docs/seminario1/entrevistas/entrevista_4.md
docs/seminario1/entrevistas/entrevista_5.md

Resolve #20 
Adiciona o documento de entrevista, incluindo a elaboração do roteiro, coleta de respostas e requisistos elicitados. Foi criado um documento geral com o roteiro da entrevista e resultados, além de outros documentos para cada entrevista realizada.

Documento de Entrevistas

---

docs/seminario1/identidade-visual.md

Resolve #
Issue #36 
Documento de Identidade Visual, apresentando cores e tipografia do projeto.
Revisar se a identidade visual apresentada condiz com o projeto, e se há algum erro de português.

Identidade visual

---

docs/seminario1/priorizacao.md

#31 
Foi feito o documento de priorização MoSCoW
Rodar a branch e verificar se faz sentido as priorizações e os requisitos, se não tem repetidos tbm

Priorização

---

docs/seminario1/tap.md

#35 
Foi feito o documento de TAP.
* Verificar erros ortográficos
* Verificar padronização do documento

Documento tap

---

docs/sprints/sprint01/sprint01-planning.md
docs/sprints/sprint01/sprint01-review.md
docs/sprints/sprint02/sprint02-planning.md

Resolves #15 
Documentação referente à sprint 1, contendo o planning e o review.

Documentacao sprint 1

---

docs/seminario1/gerenciamento-de-riscos.md
docs/seminario1/politica-contribuicao.md

#27 
Foi feito o documento de riscos e arrumei a padronização do documento de politicas
Olhar os dois documentos e ver se está certo

Gerenciamento riscos

---

docs/Apresentacoes/entrega-1.md
mkdocs.yml

Resolve #51 
Adicionando vídeos da apresentação 1
Vê se os vídeos estão funcionando.

Adicionando vídeos da apresentação 1

---

docs/1-Base/Processos-Metodologias-Abordagens/Metodologia.md
docs/1-Base/Processos-Metodologias-Abordagens/Modelagem-BPMN.md
docs/1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/5W2H.md
docs/1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Design-Sprint.md
docs/1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Ishikawa.md
docs/1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Mapa-Mental.md
docs/1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Prototipo-Baixa-Fidelidade.md
docs/1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Rich-Picture.md
docs/5-Extra/Base/Identidade-Visual.md
docs/5-Extra/Base/Personas.md
docs/5-Extra/Base/Politica-Contribuicao.md
docs/5-Extra/Base/Tecnicas-Elicitacao/Benchmarking.md
docs/5-Extra/Base/Tecnicas-Elicitacao/Brainstorming.md
docs/5-Extra/Base/Tecnicas-Elicitacao/Entrevistas/Roteiro-Entrevista.md
docs/5-Extra/Base/Tecnicas-Elicitacao/Introspeccao.md
docs/5-Extra/Base/Tecnicas-Elicitacao/NFR-Framework.md
docs/5-Extra/Base/Tecnicas-Elicitacao/Questionario.md
docs/5-Extra/Base/Tecnicas-Elicitacao/Storytelling.md
docs/5-Extra/Sprints/Sprint-01/Review-01.md

Ajuste dos caminhos das imagens e arquivos
Verificar se ta tudo ok

Ajuste caminhos das pastas

---

docs/1-Base/Projeto-Nao-Orientado-Abordagens-Especificas/Priorizacao-MOSCOW.md

O documento Moscow prioriza Requisitos e não User Stories.

(FIX) Substituindo US por REQ

---

docs/seminario1/lexicos.md

Resolves #49 
Adiciona o documento de Glossário e Léxicos

Documento de Glossário e Léxicos

---

docs/2-Modelagem/Modelagem Ágil/Backlog.md
mkdocs.yml

Resolve #65 
Foi criado o backlog do produto com a definição dos épicos, features e histórias de usuários.

Backlog do Produto

---

docs/5-Extra/Sprints/Sprint-02/Planning-02.md
docs/5-Extra/Sprints/Sprint-02/Review-02.md
docs/sprints/sprint02/sprint02-planning.md

Resolve #24 
Documentação de planejamento e revisão referente à sprint 2.
Velocity foi removido devido a organização do zenhub

Documentação sprint 2

---

docs/2-Modelagem/extras/Prototipo-Alta-Fidelidade.md
mkdocs.yml

Resolve #78 
Desenvolve e adiciona o documento do Protótipo de Alta FIdelidade

Protótipo de Alta Fidelidade

---

docs/Apresentacoes/entrega-2.md
mkdocs.yml

Resolve #91  
Adicionando vídeos da apresentação 2.
Vê se os vídeos estão funcionando.

Adicionando vídeos da apresentação 2

---

README.md

Entrega 2 (continuação do PR #92)

---

LICENSE

Tínhamos decidido essa licença no começo do semestre mas esqueci de colocá-la.
Ler a licença e ver se concorda.

Adicionando licença GPLv3

---

docs/Sprints/Sprint-05/Planning-05.md
docs/Sprints/Sprint-05/Review-05.md
mkdocs.yml

Resolve #95 
Documentação de planejamento e revisão referente à sprint 5.

Documentação sprint 5

---

docs/3-Padroes-de-Projeto/GRASPs/Padroes-Adotados-no-Projeto.md
docs/3-Padroes-de-Projeto/GRASPs/Padroes-Nao-Adotados-no-Projeto.md

Resolve #99 
Cria o documento de padrões de projetos GRASPs.

Cria documento de padrões de projetos GRASPs

---

docs/3-Padroes-de-Projeto/GoFs/Estruturais/Padroes-Adotados-no-Projeto.md
docs/3-Padroes-de-Projeto/GoFs/Estruturais/Padroes-Nao-Adotados-no-Projeto.md

Resolve #104 
Cria documento de Gofs estruturais adotados e não adotados no projeto

Gofs estruturais

---

docs/Sprints/Sprint-06/Planning-06.md
docs/Sprints/Sprint-06/Review-06.md
mkdocs.yml

Resolve #106 
Documentação de planejamento e revisão referente à sprint 6.

Documentação sprint 6

---

docs/Sprints/Sprint-07/Planning-07.md
docs/Sprints/Sprint-07/Review-07.md
mkdocs.yml

Resolve #106 
Documentação de planejamento e revisão referente à sprint 7.

Documentação sprint 7

---

docs/3-Padroes-de-Projeto/GoFs/Criacionais/Padroes-Adotados-no-Projeto.md
docs/3-Padroes-de-Projeto/GoFs/Criacionais/Padroes-Nao-Adotados-no-Projeto.md

Resolve #101 
Cria documento de GoFs criacionais, dividindo entre padrões adotados ou não no projeto, com justificativas.
Deixamos a justificativa do Factory Method um pouco genérica, para ser complementada após a adição do código.

GoFs Criacionais

---

docs/2-Modelagem/extras/arquitetura.md

Resolve #120 
Adicionando nova motivação arquitetural.

Adicionando nova motivação arquitetural

---

docs/2-Modelagem/extras/arquitetura.md

120 altera doc arquitetura

---

docs/3-Padroes-de-Projeto/GRASPs/Padroes-Adotados-no-Projeto.md
docs/3-Padroes-de-Projeto/GRASPs/Padroes-Nao-Adotados-no-Projeto.md
docs/3-Padroes-de-Projeto/GoFs/Comportamentais/Padroes-Adotados-no-Projeto.md
docs/3-Padroes-de-Projeto/GoFs/Comportamentais/Padroes-Nao-Adotados-no-Projeto.md
docs/3-Padroes-de-Projeto/GoFs/Criacionais/Padroes-Adotados-no-Projeto.md
docs/3-Padroes-de-Projeto/GoFs/Estruturais/Padroes-Adotados-no-Projeto.md

Resolve #107 
Adição de código exemplo de padrões de projeto GRASPs

Adição de código exemplo de padrões de projeto GRASPs

---

docs/Sprints/Sprint-08/Planning-08.md
docs/Sprints/Sprint-08/Review-08.md
mkdocs.yml

Resolve #115 
Documentação de planejamento e revisão referente à sprint 8.

Documentação sprint 8

---

docs/Sprints/Sprint-08/Review-08.md
docs/Sprints/Sprint-09/Planning-09.md
docs/Sprints/Sprint-09/Review-09.md
mkdocs.yml

Resolve #126 
Documentação de planejamento e revisão referente à sprint 9.

Documentação sprint 9
